[package]
name = "twitch_highway"
version = "0.2.0"
authors = ["m3id"]
edition = "2021"
description = "Twitch API"
documentation = "https://docs.rs/twitch_highway"
repository = "https://github.com/m3idnotfree/twitch_highway.git"
license = "MIT"
keywords = ["twitch", "api", "streaming", "helix", "oauth"]
categories = ["api-bindings", "web-programming"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
ads = []
analytics = []
bits = []
ccls = []
channel-points = []
channels = []
charity = []
chat = []
clips = []
conduits = []
entitlements = []
extensions = []
eventsub = []
games = []
goals = []
guest-star = []
hype-train = []
moderation = []
polls = []
predictions = []
raid = []
schedule = []
search = []
streams = []
subscriptions = []
teams = []
users = []
videos = []
whispers = []
mock-api = ["subscriptions", "streams", "videos", "teams"]
full = [
  "ads",
  "analytics",
  "bits",
  "ccls",
  "channel-points",
  "channels",
  "charity",
  "chat",
  "clips",
  "entitlements",
  "extensions",
  "eventsub",
  "games",
  "goals",
  "guest-star",
  "hype-train",
  "moderation",
  "polls",
  "predictions",
  "raid",
  "schedule",
  "search",
  "streams",
  "subscriptions",
  "teams",
  "users",
  "videos",
  "whispers",
]

[dependencies]
asknothingx2-util = { version = "0.1.7", features = ["api", "oauth", "serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
http-serde = "2.1.1"
itoa = "1.0.15"
reqwest = "0.12.22"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
twitch_oauth_token = { version = "2.0.1" }
url = "2.5.4"


[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "1.43.0", features = ["full"] }
wiremock = "0.6.4"
