[package]
name = "twitch_highway"
version = "0.0.1"
authors = ["m3id"]
edition = "2021"
description = "Twitch Api reqest Http"
license = "MIT OR Apache-2.0"
repository = "https://github.com/m3idnotfree/twitch_highway.git"
keywords = ["twitch"]


[dependencies]
reqwest = { version = "0.11.24", default_features = false, features = [
  "json",
  "rustls-tls",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
url = "2.5.0"
