[package]
name = "twitch_highway"
version = "0.0.10"
authors = ["m3id"]
edition = "2021"
description = "Twitch Api reqest Http"
license = "MIT"
repository = "https://github.com/m3idnotfree/twitch_highway.git"
keywords = ["twitch"]

[features]
default = []
ads = []
analytics = []
bits = []
test = ["types"]
channel_points = []
full = ["chat", "eventsub", "users", "types", "test"]

[dependencies]
anyhow = "1.0.95"
asknothingx2-util = { version = "0.0.13", features = ["api", "oauth", "serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
http-serde = "2.1.1"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.9"
url = "2.5.4"
serde_json = "1.0.134"
asknothingx2-eventsub = { version = "0.0.9", features = ["twitch"] }
twitch_oauth_token = { version = "1.1.2", default-features = false, features = ["types"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
twitch_oauth_token = { version = "1.1.2", features = ["full"] }
