[package]
name = "twitch_highway"
version = "0.0.4"
authors = ["m3id"]
edition = "2021"
description = "Twitch Api reqest Http"
license = "MIT"
repository = "https://github.com/m3idnotfree/twitch_highway.git"
keywords = ["twitch"]

[features]
default = ["full"]
chat = []
eventsub = []
users = []
full = ["chat", "eventsub", "users"]

[dependencies]
anyhow = "1.0.93"
asknothingx2-util = { version = "0.0.11", features = ["api", "oauth"] }
serde = { version = "1.0.214", features = ["derive"] }
thiserror = "2.0.3"
url = "2.5.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
