[package]
name = "twitch_highway"
version = "0.0.10"
authors = ["m3id"]
edition = "2021"
description = "Twitch Api reqest Http"
license = "MIT"
repository = "https://github.com/m3idnotfree/twitch_highway.git"
keywords = ["twitch"]

[features]
default = []
ads = []
analytics = []
bits = []
ccls = []
channel-points = []
channels = []
charity = []
chat = []
clips = []
entitlements = []
# eventsub = []
extensions = []
games = []
goals = []
guest-star = []
hype-train = []
moderation = []
polls = []
predictions = []
raid = []
schedule = []
search = []
streams = []
subscriptions = []
teams = []
users = []
videos = []
whispers = []
test = []
full = [
  "ads",
  "analytics",
  "bits",
  "ccls",
  "channel-points",
  "channels",
  "charity",
  "chat",
  "clips",
  "entitlements",
  # "eventsub",
  "extensions",
  "games",
  "goals",
  "guest-star",
  "hype-train",
  "moderation",
  "polls",
  "predictions",
  "raid",
  "schedule",
  "search",
  "streams",
  "subscriptions",
  "teams",
  "users",
  "videos",
  "whispers",
]

[dependencies]
asknothingx2-eventsub = { version = "0.0.9", features = ["twitch"] }
asknothingx2-util = { version = "0.0.28", features = ["api", "oauth", "serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
http-serde = "2.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.11"
twitch_oauth_token = { version = "1.1.10", default-features = false, features = ["types"] }
url = "2.5.4"

[dev-dependencies]
twitch_oauth_token = { version = "1.1.10", features = ["full"] }
dotenv = "0.15.0"
pretty_assertions = "1.4.1"
tokio = { version = "1.43.0", features = ["full"] }
