[package]
name = "twitch_highway"
version = "0.0.4"
authors = ["m3id"]
edition = "2021"
description = "Twitch Api reqest Http"
license = "MIT"
repository = "https://github.com/m3idnotfree/twitch_highway.git"
keywords = ["twitch"]

[features]
default = ["full"]
chat = []
eventsub = []
users = []
test = []
full = ["chat", "eventsub", "users"]

[dependencies]
anyhow = "1.0.94"
asknothingx2-util = { version = "0.0.11", features = ["api", "oauth"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.7"
url = "2.5.4"
serde_json = "1.0.133"

[dev-dependencies]
pretty_assertions = "1.4.1"
serde_json = "1.0.133"
