#![cfg(feature = "guest-star")]

#[macro_use]
mod common;

use twitch_highway::{
    guest_star::{GroupLayout, GuestStarAPI, GustStarSettingRequest, UpdateSlotSettingsRequest},
    types::{BroadcasterId, ModeratorId},
};

api_test!(
    get_channel_guest_star_settings,
    [
        &BroadcasterId::from("932104"),
        &ModeratorId::from("9321049")
    ]
);
api_test!(
    update_channel_guest_star_settings,
    [
        &BroadcasterId::from("9321049"),
        GustStarSettingRequest::new().group_layout(GroupLayout::TILED_LAYOUT)
    ]
);
api_test!(
    get_guest_star_session,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049")
    ]
);
api_test!(create_guest_star_session, [&BroadcasterId::from("9321049")]);
api_test!(
    end_guest_star_session,
    [
        &BroadcasterId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI"
    ]
);
api_test!(
    get_guest_star_invites,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI"
    ]
);
api_test!(
    send_guest_star_invite,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "144601104"
    ]
);
api_test!(
    delete_guest_star_invite,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "144601104"
    ]
);
api_test!(
    assign_guest_star_slot,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "144601104",
        "1"
    ]
);
api_test!(
    update_guest_star_slot,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "1",
        Some("2")
    ]
);
api_test!(
    delete_guest_star_slot,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "144601104",
        "1",
        None
    ]
);
api_test!(
    update_guest_star_slot_settings,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "1",
        UpdateSlotSettingsRequest::new().is_audio_enabled(false)
    ]
);

api_test!(extra
    update_channel_guest_star_settings,
    update_channel_guest_star_settings2,
    [
        &BroadcasterId::from("9321049"),
        GustStarSettingRequest::new().is_moderator_send_live_enabled(false)
    ]
);
api_test!(extra
    update_channel_guest_star_settings,
    update_channel_guest_star_settings3,
    [
        &BroadcasterId::from("9321049"),
        GustStarSettingRequest::new().slot_count(6)
    ]
);
api_test!(extra
    update_channel_guest_star_settings,
    update_channel_guest_star_settings4,
    [
        &BroadcasterId::from("9321049"),
        GustStarSettingRequest::new().regenerate_browser_sources(true)
    ]
);

api_test!(extra
    update_guest_star_slot_settings,
    update_guest_star_slot_settings2,
    [
        &BroadcasterId::from("9321049"),
        &ModeratorId::from("9321049"),
        "2KFRQbFtpmfyD3IevNRnCzOPRJI",
        "1",
        UpdateSlotSettingsRequest::new().is_live(true)
    ]
);
